-- ============================================================
-- Control mappings for UC-006 through UC-015 (10 use cases x 20 controls = 200 rows)
-- ============================================================
-- Judgments based on what each use case's source actually disclosed
-- (see ai_use_cases.notes). Run after 04_seed_controls.sql,
-- 09_seed_use_cases_batch2.sql, 11_seed_use_cases_batch3.sql,
-- 13_seed_use_cases_batch4.sql.

USE CATALOG ai_governance;

INSERT INTO controls.use_case_controls VALUES
-- UC-006: Services Australia -- domains disclosed, explicit "no AI processes claims"
('UC-006','CTRL-001','partial','General DTA policy applies; no agency-specific written AI policy disclosed'),
('UC-006','CTRL-002','not_implemented','No accountable role named for this use case'),
('UC-006','CTRL-003','not_implemented','No impact assessment disclosed'),
('UC-006','CTRL-004','not_implemented','No lifecycle stage detail disclosed'),
('UC-006','CTRL-005','not_implemented','No lineage detail disclosed'),
('UC-006','CTRL-006','not_implemented','No model card equivalent disclosed'),
('UC-006','CTRL-007','implemented','Explicit statement that AI does not process claims -- a clear intended-use restriction'),
('UC-006','CTRL-008','not_applicable','No third-party vendor named'),
('UC-006','CTRL-101','not_implemented','No accountable executive named'),
('UC-006','CTRL-102','partial','Aligns with AI Ethics Principles and national assurance framework generally'),
('UC-006','CTRL-103','not_implemented','No risk tolerance statement disclosed'),
('UC-006','CTRL-104','partial','Domains named (decision making, service delivery) but not full context documentation'),
('UC-006','CTRL-105','not_implemented','No stakeholder mapping disclosed'),
('UC-006','CTRL-106','not_implemented','No risk categorisation process disclosed'),
('UC-006','CTRL-107','not_implemented','No performance metrics disclosed'),
('UC-006','CTRL-108','not_implemented','No fairness testing disclosed'),
('UC-006','CTRL-109','not_implemented','No explainability mechanism disclosed'),
('UC-006','CTRL-110','not_implemented','No review cadence disclosed'),
('UC-006','CTRL-111','not_implemented','No incident response process disclosed'),
('UC-006','CTRL-112','implemented','Human oversight explicitly retained, AI excluded from claims processing'),

-- UC-007: ABS -- multiple AI uses, self-assessed lower risk
('UC-007','CTRL-001','partial','Compliance statement citing DTA policy and legislation, no dedicated AI policy document disclosed'),
('UC-007','CTRL-002','not_implemented','No accountable role named'),
('UC-007','CTRL-003','not_implemented','No impact assessment disclosed'),
('UC-007','CTRL-004','not_implemented','No lifecycle detail disclosed'),
('UC-007','CTRL-005','not_implemented','No lineage detail disclosed'),
('UC-007','CTRL-006','partial','Self-assessment of "lower potential risk" functions as a partial transparency artefact'),
('UC-007','CTRL-007','implemented','Three distinct uses explicitly scoped: classification, Census chatbot, content drafting'),
('UC-007','CTRL-008','not_applicable','No third-party vendor named'),
('UC-007','CTRL-101','not_implemented','No accountable executive named'),
('UC-007','CTRL-102','partial','Compliance statement disclosed, not a dedicated risk management policy'),
('UC-007','CTRL-103','not_implemented','No risk tolerance statement disclosed'),
('UC-007','CTRL-104','implemented','Purpose of each of the three AI uses explicitly documented'),
('UC-007','CTRL-105','not_implemented','No stakeholder mapping disclosed'),
('UC-007','CTRL-106','partial','Self-assessment as lower risk implies some categorisation exercise'),
('UC-007','CTRL-107','not_implemented','No ongoing performance metrics disclosed'),
('UC-007','CTRL-108','not_implemented','No fairness testing disclosed'),
('UC-007','CTRL-109','partial','Framed as transparent/traceable, a partial explainability claim'),
('UC-007','CTRL-110','not_implemented','No review cadence disclosed'),
('UC-007','CTRL-111','not_implemented','No incident response process disclosed'),
('UC-007','CTRL-112','not_implemented','No human-in-loop detail disclosed for the chatbot specifically'),

-- UC-008: ASIC -- domain-level only, weakest disclosure of the government cases
('UC-008','CTRL-001','not_implemented','No specific policy document disclosed beyond general compliance statement'),
('UC-008','CTRL-002','not_implemented','No accountable role named'),
('UC-008','CTRL-003','not_implemented','Not disclosed'),
('UC-008','CTRL-004','not_implemented','Not disclosed'),
('UC-008','CTRL-005','not_implemented','Not disclosed'),
('UC-008','CTRL-006','not_implemented','Not disclosed'),
('UC-008','CTRL-007','not_implemented','No specific use case or restriction disclosed'),
('UC-008','CTRL-008','not_applicable','No vendor named'),
('UC-008','CTRL-101','not_implemented','Not disclosed'),
('UC-008','CTRL-102','partial','Mandatory staff training and DTA policy compliance disclosed'),
('UC-008','CTRL-103','not_implemented','Not disclosed'),
('UC-008','CTRL-104','not_implemented','Not disclosed'),
('UC-008','CTRL-105','not_implemented','Not disclosed'),
('UC-008','CTRL-106','not_implemented','Not disclosed'),
('UC-008','CTRL-107','not_implemented','Not disclosed'),
('UC-008','CTRL-108','not_implemented','Not disclosed'),
('UC-008','CTRL-109','not_implemented','Not disclosed'),
('UC-008','CTRL-110','not_implemented','Not disclosed'),
('UC-008','CTRL-111','not_implemented','Not disclosed'),
('UC-008','CTRL-112','not_implemented','Not disclosed'),

-- UC-009: AIC -- genuine low-risk contrast case, explicit scope limitation
('UC-009','CTRL-001','implemented','Statement explicitly applies the OECD AI definition and DTA policy'),
('UC-009','CTRL-002','not_implemented','No accountable role named'),
('UC-009','CTRL-003','not_applicable','No public-facing or significant-impact use to assess'),
('UC-009','CTRL-004','not_implemented','Not disclosed'),
('UC-009','CTRL-005','not_implemented','Not disclosed'),
('UC-009','CTRL-006','not_implemented','Not disclosed'),
('UC-009','CTRL-007','implemented','Explicitly restricted from public-facing or significantly-impactful use'),
('UC-009','CTRL-008','not_applicable','No vendor named'),
('UC-009','CTRL-101','not_implemented','No accountable executive named'),
('UC-009','CTRL-102','implemented','Explicit OECD-definition-based policy statement'),
('UC-009','CTRL-103','not_applicable','Scope explicitly excludes high-risk use'),
('UC-009','CTRL-104','implemented','Purpose (internal research) explicitly documented'),
('UC-009','CTRL-105','not_applicable','No external stakeholder impact by design'),
('UC-009','CTRL-106','not_applicable','Risk explicitly minimised by scope restriction rather than categorised'),
('UC-009','CTRL-107','not_implemented','Not disclosed'),
('UC-009','CTRL-108','not_applicable','No individual-level decisioning to test for bias'),
('UC-009','CTRL-109','not_applicable','No public-facing decision to explain'),
('UC-009','CTRL-110','not_implemented','Not disclosed'),
('UC-009','CTRL-111','not_implemented','Not disclosed'),
('UC-009','CTRL-112','implemented','Internal research use only, no automated decisioning affecting the public'),

-- UC-010: Dept of Industry, Science and Resources -- AI Safety Institute context
('UC-010','CTRL-001','implemented','Explicitly aligns with the Voluntary AI Safety Standard (AI6) plus DTA policy'),
('UC-010','CTRL-002','implemented','AI Governance Committee oversight disclosed'),
('UC-010','CTRL-003','not_implemented','No impact assessment disclosed'),
('UC-010','CTRL-004','not_implemented','Not disclosed'),
('UC-010','CTRL-005','not_implemented','Not disclosed'),
('UC-010','CTRL-006','not_implemented','Not disclosed'),
('UC-010','CTRL-007','implemented','Staff explicitly required to treat outputs as drafts, not for decision-making'),
('UC-010','CTRL-008','not_applicable','No specific vendor named'),
('UC-010','CTRL-101','implemented','AI Governance Committee functions as the accountable structure'),
('UC-010','CTRL-102','implemented','Voluntary AI Safety Standard alignment disclosed'),
('UC-010','CTRL-103','not_implemented','No specific tolerance statement disclosed'),
('UC-010','CTRL-104','partial','Internal tool use context named, not fully documented'),
('UC-010','CTRL-105','not_implemented','Not disclosed'),
('UC-010','CTRL-106','not_implemented','Not disclosed'),
('UC-010','CTRL-107','not_implemented','Not disclosed'),
('UC-010','CTRL-108','not_applicable','No individual-level decisioning'),
('UC-010','CTRL-109','not_implemented','Not disclosed'),
('UC-010','CTRL-110','not_implemented','Not disclosed'),
('UC-010','CTRL-111','not_implemented','Not disclosed'),
('UC-010','CTRL-112','implemented','Explicit human-in-loop for all AI-drafted outputs'),

-- UC-011: DFAT -- internal use, low case-specific detail
('UC-011','CTRL-001','partial','References DTA, Industry, and CSIRO guidance rather than its own dedicated policy'),
('UC-011','CTRL-002','not_implemented','No accountable role named'),
('UC-011','CTRL-003','not_implemented','Not disclosed'),
('UC-011','CTRL-004','not_implemented','Not disclosed'),
('UC-011','CTRL-005','not_implemented','Not disclosed'),
('UC-011','CTRL-006','not_implemented','Not disclosed'),
('UC-011','CTRL-007','partial','Mandatory training before access implies a scoped intended-use control'),
('UC-011','CTRL-008','partial','Copilot trial named as the underlying technology'),
('UC-011','CTRL-101','not_implemented','No accountable executive named'),
('UC-011','CTRL-102','partial','References cross-agency guidance rather than its own policy'),
('UC-011','CTRL-103','not_implemented','Not disclosed'),
('UC-011','CTRL-104','partial','Three domains named for review, not fully documented context'),
('UC-011','CTRL-105','not_implemented','Not disclosed'),
('UC-011','CTRL-106','not_implemented','Not disclosed'),
('UC-011','CTRL-107','partial','Monitoring effectiveness disclosed as a governance activity'),
('UC-011','CTRL-108','not_applicable','No individual-level decisioning'),
('UC-011','CTRL-109','not_implemented','Not disclosed'),
('UC-011','CTRL-110','not_implemented','Not disclosed'),
('UC-011','CTRL-111','not_implemented','Not disclosed'),
('UC-011','CTRL-112','partial','Mandatory training before access implies some oversight, not explicit in-loop review'),

-- UC-012: AFP official statement -- deliberately redacted capability detail
('UC-012','CTRL-001','partial','References the ANZ Responsible and Ethical AI Framework and an internal National Guideline'),
('UC-012','CTRL-002','not_implemented','No accountable role named (capability detail withheld)'),
('UC-012','CTRL-003','not_implemented','Not disclosed'),
('UC-012','CTRL-004','not_implemented','Not disclosed'),
('UC-012','CTRL-005','not_implemented','Not disclosed'),
('UC-012','CTRL-006','not_implemented','Explicitly withheld for operational security reasons'),
('UC-012','CTRL-007','not_implemented','Specific use cases explicitly not disclosed'),
('UC-012','CTRL-008','not_implemented','Not disclosed'),
('UC-012','CTRL-101','not_implemented','Not disclosed'),
('UC-012','CTRL-102','implemented','Internal National Guideline governance instrument explicitly referenced'),
('UC-012','CTRL-103','not_implemented','Not disclosed'),
('UC-012','CTRL-104','not_implemented','Context explicitly withheld'),
('UC-012','CTRL-105','not_implemented','Not disclosed'),
('UC-012','CTRL-106','not_implemented','Not disclosed'),
('UC-012','CTRL-107','not_implemented','Not disclosed'),
('UC-012','CTRL-108','not_implemented','Not disclosed'),
('UC-012','CTRL-109','not_implemented','Explicitly not disclosed by design'),
('UC-012','CTRL-110','not_implemented','Not disclosed'),
('UC-012','CTRL-111','not_implemented','Not disclosed'),
('UC-012','CTRL-112','not_implemented','Not disclosed'),

-- UC-013: AFP Clearview AI -- confirmed regulatory violation
('UC-013','CTRL-001','not_implemented','No AI policy applied; informal trial predates current disclosure framework'),
('UC-013','CTRL-002','not_implemented','No accountable role disclosed for the trial'),
('UC-013','CTRL-003','not_implemented','No impact assessment conducted prior to use, per reporting'),
('UC-013','CTRL-004','not_implemented','Informal trial, no lifecycle governance disclosed'),
('UC-013','CTRL-005','not_implemented','Not disclosed'),
('UC-013','CTRL-006','not_implemented','Not disclosed'),
('UC-013','CTRL-007','not_implemented','No documented intended-use scope prior to the trial'),
('UC-013','CTRL-008','not_implemented','Free-trial vendor relationship entered without disclosed contract/review'),
('UC-013','CTRL-101','not_implemented','No accountable executive disclosed'),
('UC-013','CTRL-102','not_implemented','No risk management policy applied to this trial'),
('UC-013','CTRL-103','not_implemented','Not disclosed'),
('UC-013','CTRL-104','not_implemented','No context documentation prior to use'),
('UC-013','CTRL-105','not_implemented','No stakeholder impact assessment conducted'),
('UC-013','CTRL-106','not_implemented','No risk categorisation conducted prior to use'),
('UC-013','CTRL-107','not_implemented','Not disclosed'),
('UC-013','CTRL-108','not_implemented','No fairness testing conducted'),
('UC-013','CTRL-109','not_implemented','Not disclosed'),
('UC-013','CTRL-110','not_implemented','No review process in place before public disclosure forced discontinuation'),
('UC-013','CTRL-111','partial','Trial was discontinued following public disclosure -- a reactive, not proactive, incident response'),
('UC-013','CTRL-112','not_implemented','No human oversight process disclosed for individual matches'),

-- UC-014: WA Police live facial recognition trial
('UC-014','CTRL-001','not_implemented','No AI policy referenced in reporting'),
('UC-014','CTRL-002','not_implemented','No accountable role disclosed'),
('UC-014','CTRL-003','not_implemented','No impact assessment disclosed prior to the trial'),
('UC-014','CTRL-004','partial','Explicitly disclosed as a pilot stage'),
('UC-014','CTRL-005','not_implemented','Not disclosed'),
('UC-014','CTRL-006','not_implemented','Not disclosed'),
('UC-014','CTRL-007','partial','Purpose (watchlist screening) is clear from reporting, formal restrictions not disclosed'),
('UC-014','CTRL-008','partial','Facial recognition vendor/technology used, not formally named or reviewed in reporting'),
('UC-014','CTRL-101','not_implemented','No accountable executive disclosed'),
('UC-014','CTRL-102','not_implemented','No risk management policy referenced'),
('UC-014','CTRL-103','not_implemented','Not disclosed'),
('UC-014','CTRL-104','partial','Purpose documented in reporting, not formally by WA Police'),
('UC-014','CTRL-105','not_implemented','A human rights expert raised stakeholder concerns externally; WA Police did not respond'),
('UC-014','CTRL-106','not_implemented','No risk categorisation disclosed'),
('UC-014','CTRL-107','implemented','Real usage statistics disclosed (alerts, arrests) during the pilot'),
('UC-014','CTRL-108','not_implemented','Fairness testing (e.g. on First Nations faces) explicitly not confirmed when asked'),
('UC-014','CTRL-109','not_implemented','Not disclosed'),
('UC-014','CTRL-110','not_implemented','Not disclosed beyond the pilot framing itself'),
('UC-014','CTRL-111','not_implemented','Not disclosed'),
('UC-014','CTRL-112','not_implemented','No human-in-loop process for individual alerts disclosed'),

-- UC-015: Telstra AskTelstra / One Sentence Summary -- internal agent-assist
('UC-015','CTRL-001','not_implemented','No Telstra-specific AI policy referenced in the vendor case study'),
('UC-015','CTRL-002','not_implemented','No accountable role disclosed'),
('UC-015','CTRL-003','not_implemented','Not disclosed'),
('UC-015','CTRL-004','not_implemented','Not disclosed'),
('UC-015','CTRL-005','not_implemented','Not disclosed'),
('UC-015','CTRL-006','not_implemented','No model card disclosed'),
('UC-015','CTRL-007','implemented','Explicitly scoped to staff-facing call summarisation and Q&A'),
('UC-015','CTRL-008','implemented','Microsoft/Azure OpenAI Service explicitly named as the vendor'),
('UC-015','CTRL-101','not_implemented','No accountable executive disclosed'),
('UC-015','CTRL-102','not_implemented','No risk policy referenced'),
('UC-015','CTRL-103','not_implemented','Not disclosed'),
('UC-015','CTRL-104','implemented','Purpose (call summarisation, staff Q&A) explicitly documented'),
('UC-015','CTRL-105','not_applicable','No external stakeholder impact -- internal tool only'),
('UC-015','CTRL-106','not_implemented','Not disclosed'),
('UC-015','CTRL-107','implemented','Time-savings and follow-up-contact metrics explicitly reported'),
('UC-015','CTRL-108','not_applicable','No individual-level decisioning about customers'),
('UC-015','CTRL-109','not_implemented','Not disclosed'),
('UC-015','CTRL-110','not_implemented','Not disclosed'),
('UC-015','CTRL-111','not_implemented','Not disclosed'),
('UC-015','CTRL-112','implemented','Human agent remains the primary customer interaction point');
