-- ============================================================
-- Control mappings for UC-016 through UC-025 (10 use cases x 20 controls = 200 rows)
-- ============================================================
-- Run after 04_seed_controls.sql and all use-case seed batches
-- through 23_seed_use_cases_batch9.sql.

USE CATALOG ai_governance;

INSERT INTO controls.use_case_controls VALUES
-- UC-016: Telstra SmartFix -- autonomous network remediation, no human-in-loop disclosed
('UC-016','CTRL-001','not_implemented','No AI policy referenced in the case study'),
('UC-016','CTRL-002','not_implemented','No accountable role disclosed'),
('UC-016','CTRL-003','not_implemented','No impact assessment disclosed for an autonomous system'),
('UC-016','CTRL-004','not_implemented','Not disclosed'),
('UC-016','CTRL-005','not_implemented','Not disclosed'),
('UC-016','CTRL-006','not_implemented','Not disclosed'),
('UC-016','CTRL-007','partial','Purpose (proactive network fix) is clear, formal restrictions not disclosed'),
('UC-016','CTRL-008','not_implemented','Not disclosed'),
('UC-016','CTRL-101','not_implemented','No accountable executive disclosed'),
('UC-016','CTRL-102','not_implemented','Not disclosed'),
('UC-016','CTRL-103','not_implemented','Not disclosed'),
('UC-016','CTRL-104','partial','Purpose documented, formal context documentation not disclosed'),
('UC-016','CTRL-105','not_applicable','Network-level technical function, not individual-level'),
('UC-016','CTRL-106','not_implemented','Not disclosed'),
('UC-016','CTRL-107','implemented','2.5 million actions/year and calls-prevented metric explicitly reported'),
('UC-016','CTRL-108','not_applicable','No individual-level decisioning about customers'),
('UC-016','CTRL-109','not_implemented','Not disclosed'),
('UC-016','CTRL-110','not_implemented','Not disclosed'),
('UC-016','CTRL-111','not_implemented','No incident response process disclosed for autonomous action failures'),
('UC-016','CTRL-112','not_implemented','Explicitly autonomous action; no human-in-loop confirmed -- flagged as a real gap given the risk score'),

-- UC-017: Telstra Assistant -- public-facing chatbot
('UC-017','CTRL-001','not_implemented','No AI policy referenced'),
('UC-017','CTRL-002','not_implemented','No accountable role disclosed'),
('UC-017','CTRL-003','not_implemented','Not disclosed'),
('UC-017','CTRL-004','not_implemented','Not disclosed'),
('UC-017','CTRL-005','not_implemented','Not disclosed'),
('UC-017','CTRL-006','not_implemented','Not disclosed'),
('UC-017','CTRL-007','partial','Purpose (customer query resolution) clear, formal restrictions not disclosed'),
('UC-017','CTRL-008','not_implemented','Underlying vendor/model not specifically named for this tool'),
('UC-017','CTRL-101','not_implemented','No accountable executive disclosed'),
('UC-017','CTRL-102','not_implemented','Not disclosed'),
('UC-017','CTRL-103','not_implemented','Not disclosed'),
('UC-017','CTRL-104','implemented','Purpose (public customer query answering) explicitly documented'),
('UC-017','CTRL-105','partial','Customers are the implied stakeholder group, not formally mapped'),
('UC-017','CTRL-106','not_implemented','Not disclosed'),
('UC-017','CTRL-107','implemented','Escalation-avoidance metric ("almost tripled") explicitly reported'),
('UC-017','CTRL-108','not_applicable','No high-stakes individual decisioning'),
('UC-017','CTRL-109','not_implemented','Not disclosed'),
('UC-017','CTRL-110','not_implemented','Not disclosed'),
('UC-017','CTRL-111','not_implemented','Not disclosed'),
('UC-017','CTRL-112','implemented','Escalation path to a human implied when the chatbot cannot resolve a query'),

-- UC-018: AI medical scribes -- documented TGA compliance gap, sourced from AHPRA
('UC-018','CTRL-001','not_implemented','No sector-wide AI policy exists; regulatory gap is the finding itself'),
('UC-018','CTRL-002','not_implemented','No accountable role at the sector level (practice-by-practice adoption)'),
('UC-018','CTRL-003','not_implemented','No pre-deployment impact assessment required or disclosed for most tools'),
('UC-018','CTRL-004','not_implemented','Not disclosed'),
('UC-018','CTRL-005','not_implemented','Not disclosed'),
('UC-018','CTRL-006','not_implemented','No model card equivalent for these tools'),
('UC-018','CTRL-007','partial','AHPRA case study documents the scope (scribing, some diagnosis suggestion) even though vendors do not'),
('UC-018','CTRL-008','not_implemented','Third-party AI scribe vendors not formally reviewed per this disclosure'),
('UC-018','CTRL-101','not_implemented','No sector-wide accountable executive'),
('UC-018','CTRL-102','not_implemented','No sector-wide risk management policy'),
('UC-018','CTRL-103','not_implemented','Not disclosed'),
('UC-018','CTRL-104','implemented','AHPRA explicitly documents the tool''s function and its regulatory implications'),
('UC-018','CTRL-105','implemented','AHPRA case study explicitly identifies patients as the affected stakeholder group'),
('UC-018','CTRL-106','implemented','AHPRA explicitly categorises hallucination as a known risk of this tool category'),
('UC-018','CTRL-107','not_implemented','No ongoing performance metrics tracked at sector level'),
('UC-018','CTRL-108','not_implemented','No fairness testing disclosed'),
('UC-018','CTRL-109','not_implemented','No explainability mechanism disclosed for AI-suggested diagnoses'),
('UC-018','CTRL-110','not_implemented','Not disclosed'),
('UC-018','CTRL-111','not_implemented','No incident response process disclosed'),
('UC-018','CTRL-112','implemented','Practitioner explicitly remains responsible for the resulting health record'),

-- UC-019: AI mammography -- secondary-sourced
('UC-019','CTRL-001','not_implemented','No policy detail disclosed in this secondary source'),
('UC-019','CTRL-002','not_implemented','No accountable role disclosed'),
('UC-019','CTRL-003','not_implemented','Not disclosed'),
('UC-019','CTRL-004','not_implemented','Not disclosed'),
('UC-019','CTRL-005','not_implemented','Not disclosed'),
('UC-019','CTRL-006','not_implemented','Not disclosed'),
('UC-019','CTRL-007','partial','Purpose (triage support, not sole diagnosis) is clear from the source'),
('UC-019','CTRL-008','partial','Aidoc and Zebra Medical Vision named as vendors, no formal review process disclosed'),
('UC-019','CTRL-101','not_implemented','No accountable executive disclosed'),
('UC-019','CTRL-102','not_implemented','Not disclosed'),
('UC-019','CTRL-103','not_implemented','Not disclosed'),
('UC-019','CTRL-104','partial','Purpose documented at a general level via the secondary source'),
('UC-019','CTRL-105','partial','Patients implied as the stakeholder group, not formally mapped'),
('UC-019','CTRL-106','not_implemented','Not disclosed'),
('UC-019','CTRL-107','implemented','94.5% accuracy figure explicitly reported (from the underlying study)'),
('UC-019','CTRL-108','not_implemented','No subgroup/demographic fairness testing disclosed'),
('UC-019','CTRL-109','not_implemented','Not disclosed'),
('UC-019','CTRL-110','not_implemented','Not disclosed'),
('UC-019','CTRL-111','not_implemented','Not disclosed'),
('UC-019','CTRL-112','implemented','Radiologist review explicitly retained; AI used for triage/support only'),

-- UC-020: Suncorp SunGPT / Single View of Claim -- staff decision-support, ethics award
('UC-020','CTRL-001','not_implemented','No Suncorp-specific AI policy document disclosed'),
('UC-020','CTRL-002','not_implemented','No accountable role disclosed'),
('UC-020','CTRL-003','partial','Ethics/responsibility award implies some internal governance review process'),
('UC-020','CTRL-004','not_implemented','Not disclosed'),
('UC-020','CTRL-005','not_implemented','Not disclosed'),
('UC-020','CTRL-006','not_implemented','Not disclosed'),
('UC-020','CTRL-007','implemented','Explicitly scoped to claims summarisation and next-step recommendation for staff'),
('UC-020','CTRL-008','implemented','Built on Databricks, explicitly named'),
('UC-020','CTRL-101','not_implemented','No accountable executive disclosed'),
('UC-020','CTRL-102','partial','Ethics/responsibility award implies a risk-aware governance posture, not a named policy'),
('UC-020','CTRL-103','not_implemented','Not disclosed'),
('UC-020','CTRL-104','implemented','Purpose (claims summary, next-step recommendation) explicitly documented'),
('UC-020','CTRL-105','not_applicable','Internal staff-facing tool, not directly customer-impacting on its own'),
('UC-020','CTRL-106','not_implemented','Not disclosed'),
('UC-020','CTRL-107','implemented','Review-time reduction (5-30 minutes) explicitly reported'),
('UC-020','CTRL-108','not_applicable','Assists staff rather than making individual decisions'),
('UC-020','CTRL-109','not_implemented','Not disclosed'),
('UC-020','CTRL-110','not_implemented','Not disclosed'),
('UC-020','CTRL-111','not_implemented','Not disclosed'),
('UC-020','CTRL-112','implemented','~1,500 claims staff use it as decision support, not a replacement for their judgement'),

-- UC-021: Suncorp automated cyclone claims -- confirmed zero manual intervention
('UC-021','CTRL-001','not_implemented','No AI policy referenced for this specific pathway'),
('UC-021','CTRL-002','not_implemented','No accountable role disclosed'),
('UC-021','CTRL-003','not_implemented','No impact assessment disclosed for a fully autonomous claims pathway'),
('UC-021','CTRL-004','not_implemented','Not disclosed'),
('UC-021','CTRL-005','not_implemented','Not disclosed'),
('UC-021','CTRL-006','not_implemented','Not disclosed'),
('UC-021','CTRL-007','partial','Scope (food spoilage claims, disaster event) is named, formal restrictions not disclosed'),
('UC-021','CTRL-008','not_implemented','Not disclosed'),
('UC-021','CTRL-101','not_implemented','No accountable executive disclosed'),
('UC-021','CTRL-102','not_implemented','Not disclosed'),
('UC-021','CTRL-103','not_implemented','Not disclosed'),
('UC-021','CTRL-104','partial','Purpose and trigger event (Cyclone Alfred) documented in the CEO''s public statement'),
('UC-021','CTRL-105','not_implemented','No stakeholder impact mapping disclosed despite direct customer payout impact'),
('UC-021','CTRL-106','not_implemented','No risk categorisation disclosed for full automation'),
('UC-021','CTRL-107','implemented','7,000+ claims figure explicitly reported'),
('UC-021','CTRL-108','not_implemented','No fairness/error-rate testing disclosed -- a real gap given full automation'),
('UC-021','CTRL-109','not_implemented','No explainability mechanism disclosed for a fully automated payout decision'),
('UC-021','CTRL-110','not_implemented','Not disclosed'),
('UC-021','CTRL-111','not_implemented','Not disclosed'),
('UC-021','CTRL-112','not_implemented','Explicitly zero manual intervention -- confirmed absence of human-in-loop'),

-- UC-022: Universities AI detection -- sector-wide, self-disclosed tool limitation
('UC-022','CTRL-001','partial','Most universities have generative AI policies, though the source notes gaps in translating them to practice'),
('UC-022','CTRL-002','not_implemented','No sector-wide accountable role disclosed'),
('UC-022','CTRL-003','not_implemented','No formal impact assessment of detection tools disclosed'),
('UC-022','CTRL-004','not_implemented','Not disclosed'),
('UC-022','CTRL-005','not_implemented','Not disclosed'),
('UC-022','CTRL-006','not_implemented','Not disclosed'),
('UC-022','CTRL-007','partial','Purpose (academic integrity flagging) is clear; explicit restriction on treating a score as proof of misconduct is not consistently disclosed'),
('UC-022','CTRL-008','not_implemented','Detection tool vendors not formally reviewed per this source'),
('UC-022','CTRL-101','not_implemented','No sector-wide accountable executive'),
('UC-022','CTRL-102','partial','Generative AI policies exist at most institutions, implementation gap explicitly noted'),
('UC-022','CTRL-103','not_implemented','Not disclosed'),
('UC-022','CTRL-104','implemented','Purpose and current adoption context explicitly documented in the source'),
('UC-022','CTRL-105','implemented','Students explicitly identified as the affected stakeholder group, including the fairness risk to them'),
('UC-022','CTRL-106','not_implemented','No formal risk categorisation process disclosed'),
('UC-022','CTRL-107','implemented','Over-50%-of-assignments statistic explicitly reported'),
('UC-022','CTRL-108','implemented','Source explicitly discloses the tool''s own false-positive/validity limitation -- rare self-disclosed finding'),
('UC-022','CTRL-109','not_implemented','No explainability mechanism for how a detection score is generated disclosed'),
('UC-022','CTRL-110','not_implemented','Not disclosed'),
('UC-022','CTRL-111','not_implemented','Not disclosed'),
('UC-022','CTRL-112','implemented','Final misconduct determination is explicitly a human academic integrity decision'),

-- UC-023: AFCA -- early-stage strategy, strong human-decision commitment
('UC-023','CTRL-001','partial','AI roadmap/strategy/governance framework explicitly in development, not yet finalised'),
('UC-023','CTRL-002','not_implemented','No accountable role named yet at this early stage'),
('UC-023','CTRL-003','not_implemented','No system deployed yet to assess'),
('UC-023','CTRL-004','partial','Explicitly at the strategy/roadmap stage, earlier than even a pilot'),
('UC-023','CTRL-005','not_applicable','No system deployed yet'),
('UC-023','CTRL-006','not_implemented','Not applicable at this stage'),
('UC-023','CTRL-007','implemented','Explicit and firm commitment that all dispute resolution decisions remain human-made'),
('UC-023','CTRL-008','not_applicable','No vendor/system named yet'),
('UC-023','CTRL-101','not_implemented','No accountable executive named yet'),
('UC-023','CTRL-102','partial','Framework development explicitly underway, not yet finalised'),
('UC-023','CTRL-103','not_implemented','Not disclosed'),
('UC-023','CTRL-104','partial','General service-delivery and internal-operations context named, not use-case specific'),
('UC-023','CTRL-105','not_implemented','Not disclosed'),
('UC-023','CTRL-106','not_implemented','Not disclosed'),
('UC-023','CTRL-107','not_applicable','No system deployed to measure yet'),
('UC-023','CTRL-108','not_applicable','No automated decisioning exists to test for bias'),
('UC-023','CTRL-109','not_applicable','No system to explain yet'),
('UC-023','CTRL-110','not_implemented','Not disclosed'),
('UC-023','CTRL-111','not_implemented','Not disclosed'),
('UC-023','CTRL-112','implemented','Explicit, strong commitment that dispute decisions remain human-made'),

-- UC-024: Medibank AI-assisted support calls + ahm chatbot
('UC-024','CTRL-001','not_implemented','No AI-specific policy disclosed in the annual report excerpt'),
('UC-024','CTRL-002','not_implemented','No accountable role named for this specific system'),
('UC-024','CTRL-003','not_implemented','Not disclosed'),
('UC-024','CTRL-004','not_implemented','Not disclosed'),
('UC-024','CTRL-005','not_implemented','Not disclosed'),
('UC-024','CTRL-006','not_implemented','Not disclosed'),
('UC-024','CTRL-007','implemented','Explicitly scoped to support-call assistance and app-based chat'),
('UC-024','CTRL-008','not_implemented','Underlying vendor/model not named'),
('UC-024','CTRL-101','not_implemented','No accountable executive named for this specific system'),
('UC-024','CTRL-102','not_implemented','Not disclosed'),
('UC-024','CTRL-103','not_implemented','Not disclosed'),
('UC-024','CTRL-104','implemented','Purpose explicitly documented in the company''s own annual report'),
('UC-024','CTRL-105','not_applicable','Customer service assistance, no individual-level high-stakes decisioning'),
('UC-024','CTRL-106','not_implemented','Not disclosed'),
('UC-024','CTRL-107','implemented','Approaching-50%-of-calls figure explicitly reported'),
('UC-024','CTRL-108','not_applicable','Assists rather than decides'),
('UC-024','CTRL-109','not_implemented','Not disclosed'),
('UC-024','CTRL-110','not_implemented','Not disclosed'),
('UC-024','CTRL-111','partial','General IT security uplift disclosed post-2022 breach, not specific to this AI system'),
('UC-024','CTRL-112','implemented','Assists human agents rather than replacing the support interaction'),

-- UC-025: Medibank speech analytics for vulnerable customers
('UC-025','CTRL-001','not_implemented','No AI-specific policy disclosed'),
('UC-025','CTRL-002','not_implemented','No accountable role named'),
('UC-025','CTRL-003','not_implemented','No impact assessment disclosed for a system inferring vulnerability'),
('UC-025','CTRL-004','not_implemented','Not disclosed'),
('UC-025','CTRL-005','not_implemented','Not disclosed'),
('UC-025','CTRL-006','not_implemented','Not disclosed'),
('UC-025','CTRL-007','partial','Purpose (vulnerable customer protection) is named, formal restrictions not disclosed'),
('UC-025','CTRL-008','not_implemented','Underlying vendor/technology not named'),
('UC-025','CTRL-101','not_implemented','No accountable executive named'),
('UC-025','CTRL-102','not_implemented','Not disclosed'),
('UC-025','CTRL-103','not_implemented','Not disclosed'),
('UC-025','CTRL-104','partial','Purpose documented at a general level in the annual report'),
('UC-025','CTRL-105','implemented','Vulnerable customers explicitly identified as the target stakeholder group'),
('UC-025','CTRL-106','not_implemented','No formal risk categorisation for the sensitivity of voice-based inference disclosed'),
('UC-025','CTRL-107','not_implemented','No ongoing accuracy/false-positive metrics disclosed'),
('UC-025','CTRL-108','not_implemented','No fairness testing across accents/speech patterns disclosed -- a real gap given the risk score'),
('UC-025','CTRL-109','not_implemented','No explainability mechanism for vulnerability flags disclosed'),
('UC-025','CTRL-110','not_implemented','Not disclosed'),
('UC-025','CTRL-111','not_implemented','Not disclosed'),
('UC-025','CTRL-112','partial','Framed as enhancing existing protection processes, implying some human follow-up, not explicitly confirmed');
